# -*- coding: utf-8 -*-
"""code soal v.tabung

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pReVRKKssSv6QMKrsTrZfBjR8Zs4rrkP
"""

!pip install streamlit
import streamlit as st
import math
import random

st.set_page_config(page_title="Soal Interaktif Volume Tabung", page_icon="🧮")

st.title("🧮 Soal Interaktif Volume Tabung (SMP)")

st.write("""
Aplikasi ini membantu siswa SMP mempelajari dan melatih soal-soal **Volume Tabung** secara interaktif.
Rumus yang digunakan adalah:

### **V = π × r² × t**
""")

# ---------------------------
# Generate Soal
# ---------------------------

def generate_soal():
    r = random.randint(5, 14)           # jari-jari 5–14 cm
    t = random.randint(10, 30)          # tinggi 10–30 cm
    volume = round(math.pi * r * r * t, 2)
    return r, t, volume

if "soal" not in st.session_state:
    st.session_state.soal = generate_soal()

r, t, jawaban_benar = st.session_state.soal

st.subheader("📘 Soal:")
st.write(f"Sebuah tabung memiliki jari-jari **{r} cm** dan tinggi **{t} cm**.")
st.write("Hitunglah volumenya (gunakan π = 3.14).")

# ---------------------------
# Input Jawaban
# ---------------------------

jawaban_siswa = st.number_input("Masukkan jawabanmu di sini:", value=0.0)

cek = st.button("Periksa Jawaban 🔍")

if cek:
    if abs(jawaban_siswa - jawaban_benar) < 0.01:
        st.success(f"Benar! 🎉 Volume tabung = {jawaban_benar} cm³")
    else:
        st.error(f"Masih salah. 😥 Jawaban yang benar adalah {jawaban_benar} cm³")

# ---------------------------
# Tombol Soal Baru
# ---------------------------

if st.button("Buat Soal Baru 🔄"):
    st.session_state.soal = generate_soal()
    st.rerun()

# ---------------------------
# Pembelajaran
# ---------------------------

st.markdown("---")
st.subheader("📘 Penjelasan Singkat")
st.write("""
Volume tabung dihitung dengan mengalikan:

- Luas alas (lingkaran) → **π × r²**
- Tinggi tabung (t)

Sehingga:

### **V = π × r² × t**
""")

st.info("Tip: Perbesar latihan dengan menekan *Buat Soal Baru*!")